### ISSUE TITLE
Update meta stuffs

### ISSUE THREAD

**Issue by Guard13007** [Guard13007/Office-Life-Simulator#104]
- [ ] Itch.io page
- [ ] devblog
- [ ] issues prioritization
- [ ] stub on my website (make one)
- [ ] reference on social media profiles(?)
- [ ] check that links are no longer using the secret key (especially side links on devblog)
- [ ] README (both our actual main branch and whatever is default visible!!)
- [ ] announce the update on YouTube and social medias
