### ISSUE TITLE
Rough Design Doc / Concepts / Ideas

### ISSUE THREAD

**Issue by Guard13007** [Guard13007/Office-Life-Simulator#2]
# Objects / Features

- [x] Email client object
      - EmailProgram class, working (slightly buggy due to LoveFrames?) (incomplete)
- [ ] Taskbar object
      - Will hold ClockProgram and to be determined other stuff (like calendar and background app icons)
- [ ] Productivity Tracker object
      - This will hold your productivity score, which is affected by the things you do that this "app" is capable of tracking, primarily, emails marked Lorem or Ipsum correctly or incorrectly, and how quickly these emails were marked, and their priority (dependent on whether the sender is a manager / customer / etc.
- [x] Clock object
      - This holds the current time and has access methods to display it, update the time, etc. Already made one. Simple, but good enough (for now).

# ToDo

- [ ] Make the Lorem and Ipsum buttons remove an email and send a signal to the Productivity Tracker.
      - [ ] From is just text, needs to also have a tag saying whether or not manager or whatever.
      - [ ] A timestamp needs to be added to the email object itself when it is received ? No. When it is sent (aka when it is created), it gets a timestamp. If you fail to receive it on time, that's your "email client"'s problem.
- [x] Clock starts at current real time, and this value is saved.
- [ ] Game keeps track of play time and saves it with the rest of your save data.
- [ ] All objects have a serialize / deserialize capability for saving / loading purposes.
      - Things like Clock have raw data to save. Things like EmailProgram have size/position/open (or hidden) values to save.
- [ ] Terminal application, with pseudo command line, to do fun things, like break the computer, or stop the Productivity Tracker from working correctly, or auto do email tasks, or stuff. Dunno yet.
- [ ] Spreadsheets app.
      - [ ] Ability to handle basic mathematics.
      - [ ] Ability to handle maths between cells.
      - [ ] Think about ways to modify the cells values + use loadstring + use environment manipulation to get powerful results (think, can actually use functions like sqrt, and advanced maths handled by Lua for me).
- [ ] Pseudo file-system for use with terminal / EmailProgram (think downloading attachments) / Spreadsheets / whatever.
- [ ] Calendar app.
      - [ ] Ability to see current month in all its glory. ..just boxes with numbers, I don't plan on anything else really
      - [ ] Extra features? Ability to see "events" upcoming that you were emailed about or whatever.
- [ ] Asteroids app. Waste time! Don't get caught. Do save a high score.
- [ ] Minesweeper. Waste time! Don't get caught, you know.
- [ ] Space invaders! Waste time! D-you know.
- [ ] Gambling minigame of guessing cards...same as the others.
- [ ] mods/ folder with API to load in custom apps and stuff made by anyone?

# Going away from the desktop

- [ ] Tiling engine based on work in Grand Theft Papercut, make it so you can leave the computer and walk around your office. Do stuff.
- [ ] Up arrow key to bring up smartphone with its own interface and apps...such as Kik, where random spam happens and funny things and meme images and stupid things.
