### ISSUE TITLE
Productivity Tracker

### ISSUE THREAD

**Issue by Guard13007** [Guard13007/Office-Life-Simulator#3]
- [x] ProductivityTrackerProgram class
      - [x] lf image in Taskbar object (not implemented) as "physical" presence
      - [x] Using Beholder, this program should listen for an "email" "Lorem" / "Ipsum" signal, which will contain the From, time, and Text of that email (or actually..just the whole fucking Email, because that's simpler and easier to extend in the future if needed)
      - [x] Internally has a statistic for productivity, as well as methods for calculating this based on "various tasks", for now, just the email shit.
      - [x] EmailProgram lorem and ipsum buttons must send a behold "email" "Lorem" / "Ipsum" signal, which contain a reference to the Email. These buttons should also delete/destroy/remove those Emails "physically" from existence. The Email object will die as its references are lost by the tracker when it is through, and by no longer being tracked by the EmailProgram.
      - [x] When right-clicked, the icon will show a menu thingie that says what your productivity score is, (and whether or not you are in danger of being fired). (Clicking this can bring up a window that is a productivity report outlining what has impacted your score?)

**Comment by Guard13007** [comment]
Everything is checked here / I am closing this. Technically not done, see issue #18
